sonar.projectKey=jfonseca9_oas-quality-pipeline
sonar.organization=jfonseca9
sonar.projectName=OAS Quality Pipeline - Wallet Duck
sonar.sources=.
sonar.inclusions=**/*.yaml,**/*.yml,**/*.ts,**/*.js
sonar.exclusions=**/node_modules/**,**/out/**,**/*.backup.yaml
sonar.externalIssuesReportPaths=sonar-issues.json
sonar.sourceEncoding=UTF-8